use lightflow::preload::*;

pub fn define() -> WorkflowSpec {
    workflow("lightflow.image.crop")
        .version("0.1.0")
        .name("Image Crop")
        .description("Crop a rectangular region from a PNG image.")
        .input("image_path", "path")
        .input_description("image_path", "Source PNG image path.")
        .input_required("image_path", true)
        .input_widget("image_path", "image")
        .input_artifact_kind("image_path", "image")
        .input("x", "integer")
        .input_description("x", "Left crop coordinate in pixels.")
        .input_required("x", false)
        .input_default_json("x", "0")
        .input_range("x", 0.0, 8192.0, 1.0)
        .input_widget("x", "number")
        .input("y", "integer")
        .input_description("y", "Top crop coordinate in pixels.")
        .input_required("y", false)
        .input_default_json("y", "0")
        .input_range("y", 0.0, 8192.0, 1.0)
        .input_widget("y", "number")
        .input("width", "integer")
        .input_description("width", "Crop width in pixels.")
        .input_required("width", true)
        .input_range("width", 1.0, 8192.0, 1.0)
        .input_widget("width", "number")
        .input("height", "integer")
        .input_description("height", "Crop height in pixels.")
        .input_required("height", true)
        .input_range("height", 1.0, 8192.0, 1.0)
        .input_widget("height", "number")
        .input("output_path", "path")
        .input_description("output_path", "Optional destination PNG path.")
        .input_required("output_path", false)
        .input_widget("output_path", "file_save")
        .input_artifact_kind("output_path", "image")
        .output("image", "artifact")
        .output_description("image", "Cropped image artifact metadata.")
        .output_artifact_kind("image", "image")
        .output("image_path", "path")
        .output_description("image_path", "Path to the cropped PNG image.")
        .output_artifact_kind("image_path", "image")
        .runtime("image_crop", "lightflow.image.crop")
        .build()
}
