use lightflow::preload::*;

pub fn define() -> WorkflowSpec {
    workflow("lightflow.text.concat")
        .version("0.1.0")
        .name("Text Concat")
        .description("Concatenate two text values or an array of text values.")
        .input("a", "text")
        .input_description("a", "First text value when items is not provided.")
        .input_required("a", false)
        .input_widget("a", "textarea")
        .input("b", "text")
        .input_description("b", "Second text value when items is not provided.")
        .input_required("b", false)
        .input_widget("b", "textarea")
        .input("items", "json")
        .input_description("items", "Optional array of values to concatenate.")
        .input_required("items", false)
        .input_widget("items", "json")
        .input("separator", "text")
        .input_description("separator", "Text inserted between concatenated values.")
        .input_required("separator", false)
        .input_default_json("separator", "\"\"")
        .input_widget("separator", "text")
        .output("text", "text")
        .output_description("text", "Concatenated text.")
        .runtime("text_concat", "lightflow.text.concat")
        .build()
}
