use lightflow::preload::*;

pub fn define() -> WorkflowSpec {
    workflow("lightflow.control.switch")
        .version("0.1.0")
        .name("Control Switch")
        .description("Select a JSON value from a cases object by selector.")
        .input("selector", "text")
        .input_description("selector", "Case key to select.")
        .input_required("selector", true)
        .input_widget("selector", "text")
        .input("cases", "json")
        .input_description("cases", "JSON object mapping selector keys to values.")
        .input_required("cases", true)
        .input_widget("cases", "json")
        .input("default", "json")
        .input_description("default", "Fallback value when selector is missing.")
        .input_required("default", false)
        .input_widget("default", "json")
        .output("value", "json")
        .output_description("value", "Selected case value.")
        .output("selected", "text")
        .output_description("selected", "Selected case key or default.")
        .runtime("control_switch", "lightflow.control.switch")
        .build()
}
