use lightflow::preload::*;

pub fn define() -> WorkflowSpec {
    workflow("lightflow.image.upscale")
        .version("0.1.0")
        .name("Image Upscale")
        .description("Upscale a PNG image by an integer scale factor.")
        .input("image_path", "path")
        .input_description("image_path", "Source PNG image path.")
        .input_required("image_path", true)
        .input_widget("image_path", "image")
        .input_artifact_kind("image_path", "image")
        .input("scale", "integer")
        .input_description("scale", "Integer upscale factor.")
        .input_required("scale", false)
        .input_default_json("scale", "2")
        .input_range("scale", 1.0, 16.0, 1.0)
        .input_widget("scale", "number")
        .input("output_path", "path")
        .input_description("output_path", "Optional destination PNG path.")
        .input_required("output_path", false)
        .input_widget("output_path", "file_save")
        .input_artifact_kind("output_path", "image")
        .output("image", "artifact")
        .output_description("image", "Upscaled image artifact metadata.")
        .output_artifact_kind("image", "image")
        .output("image_path", "path")
        .output_description("image_path", "Path to the upscaled PNG image.")
        .output_artifact_kind("image_path", "image")
        .runtime("image_upscale", "lightflow.image.upscale")
        .build()
}
