[package]
name = "lightflow-text-result"
version = "0.1.0"
edition = "2024"
description = "LightFlow standard workflow node."
license = "MIT OR Apache-2.0"
repository = "https://github.com/lightjunction/lightflow-std"
keywords = ["lightflow", "workflow"]
categories = ["development-tools"]

[package.metadata.lightflow]
runner = "lightflow-text-result-runner"

[[bin]]
name = "lightflow-text-result-runner"
path = "src/bin/runner.rs"

[dependencies]
lightflow = { workspace = true }
lightflow-std-runtime = { workspace = true }
