use lightflow::preload::*;

pub fn define() -> WorkflowSpec {
    workflow("lightflow.image.resize")
        .version("0.1.0")
        .name("Image Resize")
        .description("Resize a PNG image with nearest-neighbor sampling.")
        .input("image_path", "path")
        .input_description("image_path", "Source PNG image path.")
        .input_required("image_path", true)
        .input_widget("image_path", "image")
        .input_artifact_kind("image_path", "image")
        .input("width", "integer")
        .input_description("width", "Output width in pixels.")
        .input_required("width", true)
        .input_range("width", 1.0, 8192.0, 1.0)
        .input_widget("width", "number")
        .input("height", "integer")
        .input_description("height", "Output height in pixels.")
        .input_required("height", true)
        .input_range("height", 1.0, 8192.0, 1.0)
        .input_widget("height", "number")
        .input("output_path", "path")
        .input_description("output_path", "Optional destination PNG path.")
        .input_required("output_path", false)
        .input_widget("output_path", "file_save")
        .input_artifact_kind("output_path", "image")
        .output("image", "artifact")
        .output_description("image", "Resized image artifact metadata.")
        .output_artifact_kind("image", "image")
        .output("image_path", "path")
        .output_description("image_path", "Path to the resized PNG image.")
        .output_artifact_kind("image_path", "image")
        .runtime("image_resize", "lightflow.image.resize")
        .build()
}
